# apiVersion: networking.k8s.io/v1beta1 # for k3s < v1.19
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: production
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
# ---
# apiVersion: networking.k8s.io/v1beta1 # for k3s < v1.19
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: my-python-app
#   namespace: python-namespace
#   annotations:
#     ingress.kubernetes.io/ssl-redirect: "false"
# spec:
#   rules:
#   - host: my-python-app.com
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: python-service
#             port:
#               number: 5000