apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  namespace: python-namespace
  labels:
    app: my-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
      - name: my-python-app
        image: python:3.8
        ports:
          - containerPort: 5000
        command: ["bash", "-c"]
        args:
        - |
          pip install click==8.0.3 colorama==0.4.4 Flask==2.2.2 itsdangerous==2.1.2 Jinja2==3.1.2 MarkupSafe==2.1.1 Werkzeug==2.2.2
          python3
          from flask import Flask
          app = Flask(__name__)
          @app.route("/")
          def hello():
              return "First microservice on the cloud! (local) \t By: Alvaro Juan Gomez"
              if __name__ == "__main__":
                  app.run(debug=True, host='0.0.0.0', port=5000)
        volumeMounts:
        - mountPath: /python-app
          name: app-volume
      volumes:
      - name: app-volume
        hostPath:
          path: /python-app
